handin.zip: lang-ca/dynamics-ca.fun lang-ca/execution-context.fun lang-ca/tests/refs.lam lang-ca/tests/atomic.lam
	zip handin.zip lang-ca/dynamics-ca.fun lang-ca/execution-context.fun lang-ca/tests/refs.lam lang-ca/tests/atomic.lam
